### ISSUE TITLE
Showing this error whenever I'm trying to install with python 3

### ISSUE THREAD

**Issue by ghost** [clee704/mutagenwrapper#4]
I'm using python 3.8. Whenever i'm trying to install i'm getting this error. Mutagen was installed before. I uninstalled it. Is it still conflicting with this install?
```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-evit3pr1\\mutagen\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-evit3pr1\\mutagen\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-evit3pr1\mutagen\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-evit3pr1\mutagen\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-evit3pr1\mutagen\setup.py", line 29
        except EnvironmentError, err:
                               ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hsandt** [comment]
No, that's merely a Python 3 syntax change breaking Python 2 old syntax (you need `except EnvironmentError as err`). See https://portingguide.readthedocs.io/en/latest/exceptions.html#the-new-except-syntax

Note that the file setup.py in this case belongs to mutagen, so technically, it is the mutagen dependency that is too old (it doesn't conflict with your install; on the opposite, it tries to use an older version of mutagen (1.21) which was not compatible with Python 3.

But the project mutagenwrapper itself (which has not been updated for 9 years, or 8 years for the develop branch) also needs a Python 2-to-3 upgrade.

I found a fork that did that job (both scripts upgrade and required mutagen version upgrade): https://github.com/SteveClement/mutagenwrapper

You won't get it on official pip unless officially registered, but you can install it from the repository. To avoid a manual download + install, there is a command to install via pip directly passing the repository URL: https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch (not tried myself yet)

**Comment by hsandt** [comment]
So I tried one of the commands:

> pip install git+https://github.com/SteveClement/mutagenwrapper

It works but I got an error when mutagen 1.45 is installed:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mutagenwrapper 0.0.6.dev0 requires mutagen==1.44.0, but you have mutagen 1.45.1 which is incompatible.

Don't worry, 1.45 is still compatible with 1.44. In fact, they should probably allow mutagen>=1.44. I'll tell the fork dev, but in the meantime it should be usable (if it really bothers you, download an archive of the develop branch and modify 1.44 -> 1.45 in setup.py and requirements.txt).

**Comment by SteveClement** [comment]
I pushed some changes to make it work again. Thanks.
